POST http://localhost:8080/api/register
Accept: application/json
Content-Type: application/json

{
    "email": "teju@gmail.com",
    "password": "teju123",
    "confirmPassword": "teju123"
}

###
POST http://localhost:8080/api/login

Accept: application/json
Content-Type: application/json
{
    "email": "shiva@gmail.com",
    "password": "shiva123",
}
###

POST http://localhost:8080/api/contacts
Accept: application/json
Content-Type: application/json

{
    "name": "John Doe",
    "designation": "Software Engineer",
    "company": "ABC Inc.",
    "industry": "Technology",
    "email": "john.doe@example.com",
    "phoneNumber": "+1234567890",
    "country": "United States"
}

###
GET http://localhost:8080/api/vijay@gmail.com

Accept: application/json
Content-Type: application/json
